trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  acrLoginServer: allvysharedacr.azurecr.io
  imageName: hrms-service
  buildTag: "$(resources.pipeline.hrmsBuild.runID)"

resources:
  pipelines:
  - pipeline: hrmsrelease
    source: hrms-build-service   # MUST be exact
    trigger: none

stages:
- stage: Deploy
  jobs:
  - deployment: DeployHRMS
    environment: hrms-prod
    strategy:
      runOnce:
        deploy:
          steps:

          # ❌ DO NOT checkout repo
          # - checkout: self   <-- MUST NOT EXIST

          # 1️⃣ Download manifests (MANDATORY)
          - task: DownloadPipelineArtifact@2
            displayName: Download Manifests
            inputs:
              source: specific
              project: SWM_ROUTE_FINAL
              pipeline: hrms-build-service
              artifact: manifests
              path: $(Pipeline.Workspace)/manifests

          # 2️⃣ HARD VERIFY FILES EXIST
          - script: |
              echo "=== LISTING MANIFESTS ==="
              ls -l $(Pipeline.Workspace)/manifests
            displayName: Verify manifests exist

          # 3️⃣ Deploy
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              connectionType: azureResourceManager
              azureSubscriptionConnection: agent-route-final-sc
              azureResourceGroup: rg-allvy-core-infra
              kubernetesCluster: allvy-apps-aks
              namespace: default
              manifests: |
                $(Pipeline.Workspace)/manifests/*.yaml
              containers: |
                $(acrLoginServer)/$(imageName):$(buildTag)
              rolloutStatusTimeout: 300
