trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  acrLoginServer: allvysharedacr.azurecr.io
  imageName: hrms-service
  buildTag: "$(resources.pipeline.hrmsBuild.runID)"

resources:
  pipelines:
  - pipeline: hrmsrelease
    source: hrms-build-service   # MUST be exact
    trigger: none

stages:
- stage: Deploy
  jobs:
  - deployment: DeployHRMS
    environment: hrms-prod
    strategy:
      runOnce:
        deploy:
          steps:

          # ❌ DO NOT checkout repo
          # - checkout: self   <-- MUST NOT EXIST

          # 1️⃣ Download manifests (MANDATORY)
          - task: DownloadPipelineArtifact@2
            displayName: Download Manifests
            inputs:
              source: specific
              project: SWM-ROUTE-FINAL
              pipeline: hrms-build-service
              artifact: manifests
              path: $(Pipeline.Workspace)/manifests

          # 2️⃣ HARD VERIFY FILES EXIST
          - script: |
              echo "=== LISTING MANIFESTS ==="
              ls -la $(Pipeline.Workspace)/manifests/
              echo "=== FILES CONTENT ==="
              find $(Pipeline.Workspace)/manifests/ -name "*.yaml" -type f
            displayName: Verify manifests exist

          # 3️⃣ MANUAL VARIABLE SUBSTITUTION
          - task: PowerShell@2
            displayName: Replace Variables in Secrets
            inputs:
              targetType: 'inline'
              script: |
                $secretsFile = "$(Pipeline.Workspace)/manifests/secrets.yaml"
                $content = Get-Content $secretsFile -Raw
                $content = $content -replace '#{DATABASE_URL}#', '$(DATABASE_URL)'
                $content = $content -replace '#{SECRET_KEY}#', '$(SECRET_KEY)'
                $content = $content -replace '#{SMTP_SERVER}#', '$(SMTP_SERVER)'
                $content = $content -replace '#{SMTP_PORT}#', '$(SMTP_PORT)'
                $content = $content -replace '#{SMTP_USERNAME}#', '$(SMTP_USERNAME)'
                $content = $content -replace '#{SMTP_PASSWORD}#', '$(SMTP_PASSWORD)'
                $content = $content -replace '#{FROM_EMAIL}#', '$(FROM_EMAIL)'
                $content = $content -replace '#{FRONTEND_URL}#', '$(FRONTEND_URL)'
                $content = $content -replace '#{CORS_ORIGINS}#', '$(CORS_ORIGINS)'
                Set-Content $secretsFile $content
                Write-Host "Variables replaced in secrets.yaml"

          # 4️⃣ Deploy
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              enableRolloutStatus: false
              connectionType: azureResourceManager
              azureSubscriptionConnection: agent-route-final-sc
              azureResourceGroup: rg-allvy-core-infra
              kubernetesCluster: allvy-apps-aks
              namespace: default
              manifests: |
                $(Pipeline.Workspace)/manifests/manifests/service.yaml
                $(Pipeline.Workspace)/manifests/manifests/deployment.yaml
                $(Pipeline.Workspace)/manifests/manifests/secrets.yaml
