"""add compliance documents table

Revision ID: 1350a68a24ad
Revises: 
Create Date: 2025-12-03 13:08:24.242049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1350a68a24ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_documents_and_policy_management',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_document', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=50), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("category IN ('Policy','Compliance','Legal','Training')", name='check_category'),
    sa.PrimaryKeyConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_documents_and_policy_management')
    # ### end Alembic commands ###
