"""add_policy_master_table

Revision ID: a23fbaabde77
Revises: ef5cb2effd53
Create Date: 2025-12-03 14:36:46.336859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23fbaabde77'
down_revision = 'ef5cb2effd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('working_hours_per_day', sa.Float(), nullable=False),
    sa.Column('working_days_per_week', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('mark_late_after_minutes', sa.Integer(), nullable=False),
    sa.Column('half_day_hours', sa.Float(), nullable=False),
    sa.Column('auto_deduct_for_absence', sa.Boolean(), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('overtime_multiplier_weekdays', sa.Float(), nullable=True),
    sa.Column('overtime_multiplier_weekend', sa.Float(), nullable=True),
    sa.Column('require_check_in', sa.Boolean(), nullable=False),
    sa.Column('require_check_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('attendance', sa.Column('punch_in', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('punch_out', sa.Time(), nullable=True))
    op.add_column('attendance', sa.Column('work_hours', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('attendance', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'status')
    op.drop_column('attendance', 'work_hours')
    op.drop_column('attendance', 'punch_out')
    op.drop_column('attendance', 'punch_in')
    op.drop_table('policy_master')
    # ### end Alembic commands ###
