"""Fix employee_id foreign key

Revision ID: d51ec66a44cc
Revises: add_pdf_path_001
Create Date: 2025-12-10 17:57:18.376288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd51ec66a44cc'
down_revision = 'add_pdf_path_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_edit_requests')
    op.drop_index('ix_employee_balances_id', table_name='employee_balances')
    op.drop_table('employee_balances')
    op.drop_constraint('assets_employee_id_fkey', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'employees', ['employee_id'], ['employee_id'])
    op.alter_column('bank_details', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'compliance_documents_and_policy_management', 'employees', ['uploaded_by'], ['employee_id'])
    op.alter_column('educational_qualifications', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_edu_employee', table_name='educational_qualifications')
    op.alter_column('employee_documents', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('employee_documents', 'file_name')
    op.create_index(op.f('ix_employee_expenses_expense_id'), 'employee_expenses', ['expense_id'], unique=False)
    op.drop_constraint('employee_expenses_employee_id_fkey', 'employee_expenses', type_='foreignkey')
    op.alter_column('employee_personal_details', 'employee_email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'employee_address',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('employee_work_experience', 'experience_designation',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('employee_work_experience', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('employee_work_experience', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'joining_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'reporting_manager',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('employees', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employees', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employees', 'employee_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('employees', 'annual_ctc',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_employees_department', table_name='employees')
    op.drop_index('idx_employees_shift', table_name='employees')
    op.drop_constraint('employees_department_id_fkey', 'employees', type_='foreignkey')
    op.drop_constraint('employees_shift_id_fkey', 'employees', type_='foreignkey')
    op.drop_column('employees', 'full_name')
    op.drop_column('employees', 'active_status')
    op.create_index(op.f('ix_job_titles_job_title_id'), 'job_titles', ['job_title_id'], unique=False)
    op.create_index(op.f('ix_leave_management_leave_id'), 'leave_management', ['leave_id'], unique=False)
    op.alter_column('payroll_setup', 'pdf_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_payroll_employee_id', table_name='payroll_setup')
    op.drop_index('idx_payroll_month', table_name='payroll_setup')
    op.create_index(op.f('ix_payroll_setup_created_at'), 'payroll_setup', ['created_at'], unique=False)
    op.create_index(op.f('ix_payroll_setup_employee_id'), 'payroll_setup', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_setup_month'), 'payroll_setup', ['month'], unique=False)
    op.create_index(op.f('ix_payroll_setup_payroll_id'), 'payroll_setup', ['payroll_id'], unique=False)
    op.drop_constraint('payroll_setup_employee_id_fkey', 'payroll_setup', type_='foreignkey')
    op.drop_column('payroll_setup', 'is_pf_locked')
    op.drop_column('payroll_setup', 'is_pt_locked')
    op.drop_column('payroll_setup', 'bonus_percentage')
    op.drop_column('payroll_setup', 'is_bonus_taxable')
    op.drop_column('payroll_setup', 'is_basic_taxable')
    op.drop_column('payroll_setup', 'salary_components')
    op.drop_column('payroll_setup', 'lop_amount')
    op.drop_column('payroll_setup', 'income_tax')
    op.drop_column('payroll_setup', 'is_allowance_taxable')
    op.drop_column('payroll_setup', 'is_income_tax_auto')
    op.drop_column('payroll_setup', 'is_hra_taxable')
    op.create_index(op.f('ix_policy_master_id'), 'policy_master', ['id'], unique=False)
    op.create_index(op.f('ix_policy_master_name'), 'policy_master', ['name'], unique=True)
    op.alter_column('shift_master', 'working_days',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_index(op.f('ix_shift_master_shift_id'), 'shift_master', ['shift_id'], unique=False)
    op.alter_column('time_entries', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('time_entries', 'entry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('time_entries', 'project',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('time_entries', 'task_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('time_entries', 'hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_index('idx_time_entries_id', table_name='time_entries')
    op.drop_index('idx_time_entry_date', table_name='time_entries')
    op.drop_index('idx_time_entry_employee', table_name='time_entries')
    op.create_index(op.f('ix_time_entries_time_entry_id'), 'time_entries', ['time_entry_id'], unique=False)
    op.drop_constraint('time_entries_employee_id_fkey', 'time_entries', type_='foreignkey')
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('users_employee_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_unique_constraint('users_employee_id_key', 'users', ['employee_id'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('time_entries_employee_id_fkey', 'time_entries', 'employees', ['employee_id'], ['employee_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_time_entries_time_entry_id'), table_name='time_entries')
    op.create_index('idx_time_entry_employee', 'time_entries', ['employee_id'], unique=False)
    op.create_index('idx_time_entry_date', 'time_entries', ['entry_date'], unique=False)
    op.create_index('idx_time_entries_id', 'time_entries', ['time_entry_id'], unique=False)
    op.alter_column('time_entries', 'hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('time_entries', 'task_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('time_entries', 'project',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('time_entries', 'entry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('time_entries', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_shift_master_shift_id'), table_name='shift_master')
    op.alter_column('shift_master', 'working_days',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_policy_master_name'), table_name='policy_master')
    op.drop_index(op.f('ix_policy_master_id'), table_name='policy_master')
    op.add_column('payroll_setup', sa.Column('is_hra_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('is_income_tax_auto', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('is_allowance_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('income_tax', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('lop_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('salary_components', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('is_basic_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('is_bonus_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('bonus_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('is_pt_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('payroll_setup', sa.Column('is_pf_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_foreign_key('payroll_setup_employee_id_fkey', 'payroll_setup', 'employees', ['employee_id'], ['employee_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payroll_setup_payroll_id'), table_name='payroll_setup')
    op.drop_index(op.f('ix_payroll_setup_month'), table_name='payroll_setup')
    op.drop_index(op.f('ix_payroll_setup_employee_id'), table_name='payroll_setup')
    op.drop_index(op.f('ix_payroll_setup_created_at'), table_name='payroll_setup')
    op.create_index('idx_payroll_month', 'payroll_setup', ['month'], unique=False)
    op.create_index('idx_payroll_employee_id', 'payroll_setup', ['employee_id'], unique=False)
    op.alter_column('payroll_setup', 'pdf_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_leave_management_leave_id'), table_name='leave_management')
    op.drop_index(op.f('ix_job_titles_job_title_id'), table_name='job_titles')
    op.add_column('employees', sa.Column('active_status', sa.VARCHAR(length=20), server_default=sa.text("'Active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('full_name', sa.VARCHAR(), sa.Computed("(((first_name)::text || ' '::text) || (last_name)::text)", persisted=True), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_shift_id_fkey', 'employees', 'shift_master', ['shift_id'], ['shift_id'])
    op.create_foreign_key('employees_department_id_fkey', 'employees', 'departments', ['department_id'], ['department_id'])
    op.create_index('idx_employees_shift', 'employees', ['shift_id'], unique=False)
    op.create_index('idx_employees_department', 'employees', ['department_id'], unique=False)
    op.alter_column('employees', 'annual_ctc',
               existing_type=sa.String(length=50),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('employees', 'employee_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('employees', 'shift_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('employees', 'reporting_manager',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('employees', 'joining_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employee_work_experience', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employee_work_experience', 'company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('employee_work_experience', 'experience_designation',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employee_personal_details', 'employee_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('employee_personal_details', 'employee_email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_foreign_key('employee_expenses_employee_id_fkey', 'employee_expenses', 'employees', ['employee_id'], ['employee_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employee_expenses_expense_id'), table_name='employee_expenses')
    op.add_column('employee_documents', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('employee_documents', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index('idx_edu_employee', 'educational_qualifications', ['employee_id'], unique=False)
    op.alter_column('educational_qualifications', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'compliance_documents_and_policy_management', type_='foreignkey')
    op.alter_column('bank_details', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key('assets_employee_id_fkey', 'assets', 'employees', ['employee_id'], ['employee_id'], ondelete='SET NULL')
    op.create_table('employee_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sick_leave_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('casual_leave_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('earned_leave_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sick_leave_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('casual_leave_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('earned_leave_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employee_balances_pkey'),
    sa.UniqueConstraint('employee_id', name='employee_balances_employee_id_key')
    )
    op.create_index('ix_employee_balances_id', 'employee_balances', ['id'], unique=False)
    op.create_table('profile_edit_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('requested_changes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('manager_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profile_edit_requests_pkey')
    )
    # ### end Alembic commands ###
