"""add_policy_id_to_attendance

Revision ID: d8d5d9446eba
Revises: a23fbaabde77
Create Date: 2025-12-03 14:38:47.614066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d5d9446eba'
down_revision = 'a23fbaabde77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('policy_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'policy_master', ['policy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'policy_id')
    # ### end Alembic commands ###
