"""create all hrms tables

Revision ID: ef5cb2effd53
Revises: 1350a68a24ad
Create Date: 2025-12-03 13:12:16.796298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5cb2effd53'
down_revision = '1350a68a24ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'departments' not in existing_tables:
        op.create_table('departments',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_name')
        )
    
    if 'job_titles' not in existing_tables:
        op.create_table('job_titles',
    sa.Column('job_title_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('job_title_id')
        )
    
    if 'shift_master' not in existing_tables:
        op.create_table('shift_master',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_name', sa.String(length=150), nullable=False),
    sa.Column('shift_type', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('working_days', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
        )
    
    if 'employees' not in existing_tables:
        op.create_table('employees',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('reporting_manager', sa.String(length=50), nullable=True),
    sa.Column('email_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['reporting_manager'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email_id')
        )
        op.create_index('idx_employees_department', 'employees', ['department_id'], unique=False)
        op.create_index('idx_employees_shift', 'employees', ['shift_id'], unique=False)
    
    if 'assets' not in existing_tables:
        op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('asset_name', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('assigned_employee_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Available', nullable=True),
    sa.Column('condition', sa.String(length=50), server_default='Good', nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("condition IN ('Excellent','Good','Fair')", name='check_condition'),
    sa.CheckConstraint("status IN ('Assigned','Available','Maintenance')", name='check_status'),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('serial_number')
        )
        op.create_index('idx_assets_employee', 'assets', ['assigned_employee_id'], unique=False)
    
    if 'attendance' not in existing_tables:
        op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id')
        )
        op.create_index('idx_attendance_date', 'attendance', ['attendance_date'], unique=False)
        op.create_index('idx_attendance_emp', 'attendance', ['employee_id'], unique=False)
    
    if 'bank_details' not in existing_tables:
        op.create_table('bank_details',
    sa.Column('bank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('account_holder_name', sa.String(length=50), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=15), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("account_type IN ('Savings','Current')", name='check_account_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bank_id'),
    sa.UniqueConstraint('account_number')
        )
    
    if 'educational_qualifications' not in existing_tables:
        op.create_table('educational_qualifications',
    sa.Column('edu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('course_name', sa.String(length=150), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('skill_name', sa.String(length=150), nullable=True),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edu_id')
        )
        op.create_index('idx_edu_employee', 'educational_qualifications', ['employee_id'], unique=False)
    
    if 'employee_documents' not in existing_tables:
        op.create_table('employee_documents',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='Pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
        )
    
    if 'employee_expenses' not in existing_tables:
        op.create_table('employee_expenses',
    sa.Column('expense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id')
        )
    
    if 'employee_personal_details' not in existing_tables:
        op.create_table('employee_personal_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('employee_email', sa.String(length=50), nullable=True),
    sa.Column('employee_phone', sa.String(length=20), nullable=True),
    sa.Column('employee_alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('employee_address', sa.String(length=150), nullable=True),
    sa.Column('emergency_full_name', sa.String(length=50), nullable=True),
    sa.Column('emergency_relationship', sa.String(length=50), nullable=True),
    sa.Column('emergency_primary_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_address', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
        )
    
    if 'leave_management' not in existing_tables:
        op.create_table('leave_management',
    sa.Column('leave_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('leave_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leave_id')
        )
    
    if 'onboarding_process' not in existing_tables:
        op.create_table('onboarding_process',
    sa.Column('onboarding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('shifts', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('onboarding_id')
        )
    
    if 'payroll_setup' not in existing_tables:
        op.create_table('payroll_setup',
    sa.Column('payroll_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('pay_cycle', sa.String(length=20), server_default='Monthly', nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('hra', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('allowance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('bonus_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True),
    sa.Column('is_bonus_taxable', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_allowance_taxable', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_hra_taxable', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_basic_taxable', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('provident_fund_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True),
    sa.Column('professional_tax', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('income_tax', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('lop_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('is_pf_locked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_pt_locked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_income_tax_auto', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("pay_cycle IN ('Monthly','Weekly','Biweekly')", name='check_pay_cycle'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payroll_id')
        )
    
    if 'time_entries' not in existing_tables:
        op.create_table('time_entries',
    sa.Column('time_entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('project', sa.String(length=150), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time_entry_id')
        )
        op.create_index('idx_time_entry_date', 'time_entries', ['entry_date'], unique=False)
        op.create_index('idx_time_entry_employee', 'time_entries', ['employee_id'], unique=False)
    
    if 'compliance_documents_and_policy_management' in existing_tables:
        op.create_foreign_key(None, 'compliance_documents_and_policy_management', 'employees', ['uploaded_by'], ['employee_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compliance_documents_and_policy_management', type_='foreignkey')
    op.drop_index('idx_time_entry_employee', table_name='time_entries')
    op.drop_index('idx_time_entry_date', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_table('payroll_setup')
    op.drop_table('onboarding_process')
    op.drop_table('leave_management')
    op.drop_table('employee_personal_details')
    op.drop_table('employee_expenses')
    op.drop_table('employee_documents')
    op.drop_index('idx_edu_employee', table_name='educational_qualifications')
    op.drop_table('educational_qualifications')
    op.drop_table('bank_details')
    op.drop_index('idx_attendance_emp', table_name='attendance')
    op.drop_index('idx_attendance_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('idx_assets_employee', table_name='assets')
    op.drop_table('assets')
    op.drop_index('idx_employees_shift', table_name='employees')
    op.drop_index('idx_employees_department', table_name='employees')
    op.drop_table('employees')
    op.drop_table('shift_master')
    op.drop_table('job_titles')
    op.drop_table('departments')
    # ### end Alembic commands ###
