"""add_events_holidays_table

Revision ID: fc1b400b20eb
Revises: 03d6ee40b5c9
Create Date: 2025-12-05 17:54:11.117708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc1b400b20eb'
down_revision = '03d6ee40b5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    op.drop_index('idx_employees_department', table_name='employees')
    op.drop_index('idx_employees_shift', table_name='employees')
    op.drop_table('employees')
    op.drop_table('payroll_setup')
    op.drop_table('leave_management')
    op.drop_index('idx_attendance_date', table_name='attendance')
    op.drop_index('idx_attendance_emp', table_name='attendance')
    op.drop_table('attendance')
    op.drop_table('shift_master')
    op.drop_table('compliance_documents_and_policy_management')
    op.drop_table('employee_personal_details')
    op.drop_table('job_titles')
    op.drop_table('bank_details')
    op.drop_index('idx_assets_employee', table_name='assets')
    op.drop_table('assets')
    op.drop_index('idx_time_entry_date', table_name='time_entries')
    op.drop_index('idx_time_entry_employee', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_table('employee_expenses')
    op.drop_table('employee_documents')
    op.drop_index('idx_edu_employee', table_name='educational_qualifications')
    op.drop_table('educational_qualifications')
    op.drop_table('onboarding_process')
    op.drop_constraint('policy_master_name_key', 'policy_master', type_='unique')
    op.create_index(op.f('ix_policy_master_id'), 'policy_master', ['id'], unique=False)
    op.create_index(op.f('ix_policy_master_name'), 'policy_master', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_master_name'), table_name='policy_master')
    op.drop_index(op.f('ix_policy_master_id'), table_name='policy_master')
    op.create_unique_constraint('policy_master_name_key', 'policy_master', ['name'])
    op.create_table('onboarding_process',
    sa.Column('onboarding_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('shifts', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='onboarding_process_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('onboarding_id', name='onboarding_process_pkey')
    )
    op.create_table('educational_qualifications',
    sa.Column('edu_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('institution_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('skill_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('proficiency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='educational_qualifications_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edu_id', name='educational_qualifications_pkey')
    )
    op.create_index('idx_edu_employee', 'educational_qualifications', ['employee_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('document_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('upload_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='employee_documents_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name='employee_documents_pkey')
    )
    op.create_table('employee_expenses',
    sa.Column('expense_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('expense_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='employee_expenses_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id', name='employee_expenses_pkey')
    )
    op.create_table('time_entries',
    sa.Column('time_entry_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('project', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('task_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='time_entries_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time_entry_id', name='time_entries_pkey')
    )
    op.create_index('idx_time_entry_employee', 'time_entries', ['employee_id'], unique=False)
    op.create_index('idx_time_entry_date', 'time_entries', ['entry_date'], unique=False)
    op.create_table('assets',
    sa.Column('asset_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('asset_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('assigned_employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Available'::character varying"), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(length=50), server_default=sa.text("'Good'::character varying"), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("condition::text = ANY (ARRAY['Excellent'::character varying, 'Good'::character varying, 'Fair'::character varying]::text[])", name='check_condition'),
    sa.CheckConstraint("status::text = ANY (ARRAY['Assigned'::character varying, 'Available'::character varying, 'Maintenance'::character varying]::text[])", name='check_status'),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.employee_id'], name='assets_assigned_employee_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('asset_id', name='assets_pkey'),
    sa.UniqueConstraint('serial_number', name='assets_serial_number_key')
    )
    op.create_index('idx_assets_employee', 'assets', ['assigned_employee_id'], unique=False)
    op.create_table('bank_details',
    sa.Column('bank_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('account_holder_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pan_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('aadhaar_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("account_type::text = ANY (ARRAY['Savings'::character varying, 'Current'::character varying]::text[])", name='check_account_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='bank_details_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bank_id', name='bank_details_pkey'),
    sa.UniqueConstraint('account_number', name='bank_details_account_number_key')
    )
    op.create_table('job_titles',
    sa.Column('job_title_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('salary_min', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_max', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('job_title_id', name='job_titles_pkey')
    )
    op.create_table('employee_personal_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employee_email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employee_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('employee_alternate_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('employee_address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('emergency_full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('emergency_relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('emergency_primary_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('emergency_alternate_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('emergency_address', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='employee_personal_details_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employee_personal_details_pkey'),
    sa.UniqueConstraint('employee_id', name='employee_personal_details_employee_id_key')
    )
    op.create_table('compliance_documents_and_policy_management',
    sa.Column('document_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_document', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('uploaded_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("category::text = ANY (ARRAY['Policy'::character varying, 'Compliance'::character varying, 'Legal'::character varying, 'Training'::character varying]::text[])", name='check_category'),
    sa.PrimaryKeyConstraint('document_id', name='compliance_documents_and_policy_management_pkey')
    )
    op.create_table('shift_master',
    sa.Column('shift_id', sa.INTEGER(), server_default=sa.text("nextval('shift_master_shift_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('shift_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('shift_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('working_days', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('shift_id', name='shift_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('attendance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('punch_in', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('punch_out', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('work_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='attendance_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_master.id'], name='attendance_policy_id_fkey'),
    sa.PrimaryKeyConstraint('attendance_id', name='attendance_pkey')
    )
    op.create_index('idx_attendance_emp', 'attendance', ['employee_id'], unique=False)
    op.create_index('idx_attendance_date', 'attendance', ['attendance_date'], unique=False)
    op.create_table('leave_management',
    sa.Column('leave_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('employee_used_leaves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='leave_management_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leave_id', name='leave_management_pkey')
    )
    op.create_table('payroll_setup',
    sa.Column('payroll_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pay_cycle', sa.VARCHAR(length=20), server_default=sa.text("'Monthly'::character varying"), autoincrement=False, nullable=True),
    sa.Column('basic_salary', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('hra', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('allowance', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('bonus_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('is_bonus_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_allowance_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_hra_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_basic_taxable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('provident_fund_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('professional_tax', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('income_tax', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('lop_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('is_pf_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_pt_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_income_tax_auto', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('total_earnings', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('total_deductions', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('net_salary', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("pay_cycle::text = ANY (ARRAY['Monthly'::character varying, 'Weekly'::character varying, 'Biweekly'::character varying]::text[])", name='check_pay_cycle'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='payroll_setup_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payroll_id', name='payroll_setup_pkey')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), sa.Computed("(((first_name)::text || ' '::text) || (last_name)::text)", persisted=True), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('reporting_manager', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('annual_leaves', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=True),
    sa.Column('annual_ctc', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('active_status', sa.VARCHAR(length=20), server_default=sa.text("'Active'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name='employees_department_id_fkey'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_master.shift_id'], name='employees_shift_id_fkey'),
    sa.PrimaryKeyConstraint('employee_id', name='employees_pkey'),
    sa.UniqueConstraint('email_id', name='employees_email_id_key')
    )
    op.create_index('idx_employees_shift', 'employees', ['shift_id'], unique=False)
    op.create_index('idx_employees_department', 'employees', ['department_id'], unique=False)
    op.create_table('departments',
    sa.Column('department_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('department_id', name='departments_pkey'),
    sa.UniqueConstraint('department_name', name='departments_department_name_key')
    )
    # ### end Alembic commands ###
